#include <iostream>
#include <conio.h>
#include <windows.h>
#define color SetConsoleTextAttribute
using namespace std;
int main() {
	HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
	color(hConsole, 5);
//	1
	cout<<"                                       \n";
	cout<<"                     /|*                  \n";
	cout<<"                    /_|___*                \n";
	cout<<"                   /__|___|             \n";
	cout<<"                      |___|              \n";
	color(hConsole, 6);
	cout<<"                     /*   |             \n";
	cout<<"                    /   * |            \n";
	cout<<"                   /     *             \n";
	cout<<"                   |*   /              \n";
	color(hConsole, 1);
	cout<<"                   | * /|* _________        \n";
	cout<<"                   |__/_|__*_______/      \n";
	cout<<"                   |_/__|____*____/        \n";
	cout<<"                   |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                     *__|______*/          \n";
	cout<<"                      * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	2
	color(hConsole, 5);
	cout<<"                                       \n";
	cout<<"                      /|*                  \n";
	cout<<"                     /_|___*                \n";
	cout<<"                    /__|___|             \n";
	cout<<"                       |___|              \n";
	color(hConsole, 6);
	cout<<"                      /*   |             \n";
	cout<<"                     /   * |            \n";
	cout<<"                    /     *             \n";
	cout<<"                    |*   /              \n";
	color(hConsole, 1);
	cout<<"                    | * /|* _________        \n";
	cout<<"                    |__/_|__*_______/      \n";
	cout<<"                    |_/__|____*____/        \n";
	cout<<"                    |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                      *__|______*/          \n";
	cout<<"                       * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	3
color(hConsole, 5);
	cout<<"                                       \n";
	cout<<"                       /|*                  \n";
	cout<<"                      /_|___*                \n";
	cout<<"                     /__|___|             \n";
	cout<<"                        |___|              \n";
	color(hConsole, 6);
	cout<<"                       /*   |             \n";
	cout<<"                      /   * |            \n";
	cout<<"                     /     *             \n";
	cout<<"                     |*   /              \n";
	color(hConsole, 1);
	cout<<"                     | * /|* _________        \n";
	cout<<"                     |__/_|__*_______/      \n";
	cout<<"                     |_/__|____*____/        \n";
	cout<<"                     |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                       *__|______*/          \n";
	cout<<"                        * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	4
color(hConsole, 5);
	cout<<"                                        \n";
	cout<<"                        /|*                  \n";
	cout<<"                       /_|___*                \n";
	cout<<"                      /__|___|             \n";
	cout<<"                         |___|              \n";
	color(hConsole, 6);
	cout<<"                        /*   |             \n";
	cout<<"                       /   * |            \n";
	cout<<"                      /     *             \n";
	cout<<"                      |*   /              \n";
	color(hConsole, 1);
	cout<<"                      | * /|* _________        \n";
	cout<<"                      |__/_|__*_______/      \n";
	cout<<"                      |_/__|____*____/        \n";
	cout<<"                      |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                        *__|______*/          \n";
	cout<<"                         * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	5
color(hConsole, 5);
	cout<<"                                         \n";
	cout<<"                         /|*                  \n";
	cout<<"                        /_|___*                \n";
	cout<<"                       /__|___|             \n";
	cout<<"                          |___|              \n";
	color(hConsole, 6);
	cout<<"                         /*   |             \n";
	cout<<"                        /   * |            \n";
	cout<<"                       /     *             \n";
	cout<<"                       |*   /              \n";
	color(hConsole, 1);
	cout<<"                       | * /|* _________        \n";
	cout<<"                       |__/_|__*_______/      \n";
	cout<<"                       |_/__|____*____/        \n";
	cout<<"                       |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                         *__|______*/          \n";
	cout<<"                          * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	6
color(hConsole, 5);
	cout<<"                                          \n";
	cout<<"                          /|*                  \n";
	cout<<"                         /_|___*                \n";
	cout<<"                        /__|___|             \n";
	cout<<"                           |___|              \n";
	color(hConsole, 6);
	cout<<"                          /*   |             \n";
	cout<<"                         /   * |            \n";
	cout<<"                        /     *             \n";
	cout<<"                        |*   /              \n";
	color(hConsole, 1);
	cout<<"                        | * /|* _________        \n";
	cout<<"                        |__/_|__*_______/      \n";
	cout<<"                        |_/__|____*____/        \n";
	cout<<"                        |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                          *__|______*/          \n";
	cout<<"                           * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	7
color(hConsole, 5);
	cout<<"                                          \n";
	cout<<"                           /|*                  \n";
	cout<<"                          /_|___*                \n";
	cout<<"                         /__|___|             \n";
	cout<<"                            |___|              \n";
	color(hConsole, 6);
	cout<<"                           /*   |             \n";
	cout<<"                          /   * |            \n";
	cout<<"                         /     *             \n";
	cout<<"                         |*   /              \n";
	color(hConsole, 1);
	cout<<"                         | * /|* _________        \n";
	cout<<"                         |__/_|__*_______/      \n";
	cout<<"                         |_/__|____*____/        \n";
	cout<<"                         |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                           *__|______*/          \n";
	cout<<"                            * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	8
color(hConsole, 5);
	cout<<"                                          \n";
	cout<<"                            /|*                  \n";
	cout<<"                           /_|___*                \n";
	cout<<"                          /__|___|             \n";
	cout<<"                             |___|              \n";
	color(hConsole, 6);
	cout<<"                            /*   |             \n";
	cout<<"                           /   * |            \n";
	cout<<"                          /     *             \n";
	cout<<"                          |*   /              \n";
	color(hConsole, 1);
	cout<<"                          | * /|* _________        \n";
	cout<<"                          |__/_|__*_______/      \n";
	cout<<"                          |_/__|____*____/        \n";
	cout<<"                          |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                            *__|______*/          \n";
	cout<<"                             * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	9
color(hConsole, 5);
	cout<<"                                           \n";
	cout<<"                             /|*                  \n";
	cout<<"                            /_|___*                \n";
	cout<<"                           /__|___|             \n";
	cout<<"                              |___|              \n";
	color(hConsole, 6);
	cout<<"                             /*   |             \n";
	cout<<"                            /   * |            \n";
	cout<<"                           /     *             \n";
	cout<<"                           |*   /              \n";
	color(hConsole, 1);
	cout<<"                           | * /|* _________        \n";
	cout<<"                           |__/_|__*_______/      \n";
	cout<<"                           |_/__|____*____/        \n";
	cout<<"                           |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                             *__|______*/          \n";
	cout<<"                              * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	10
color(hConsole, 5);
	cout<<"                                            \n";
	cout<<"                              /|*                  \n";
	cout<<"                             /_|___*                \n";
	cout<<"                            /__|___|             \n";
	cout<<"                               |___|              \n";
	color(hConsole, 6);
	cout<<"                              /*   |             \n";
	cout<<"                             /   * |            \n";
	cout<<"                            /     *             \n";
	cout<<"                            |*   /              \n";
	color(hConsole, 1);
	cout<<"                            | * /|* _________        \n";
	cout<<"                            |__/_|__*_______/      \n";
	cout<<"                            |_/__|____*____/        \n";
	cout<<"                            |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                              *__|______*/          \n";
	cout<<"                               * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	11
color(hConsole, 5);
	cout<<"                                             \n";
	cout<<"                               /|*                  \n";
	cout<<"                              /_|___*                \n";
	cout<<"                             /__|___|             \n";
	cout<<"                                |___|              \n";
	color(hConsole, 6);
	cout<<"                               /*   |             \n";
	cout<<"                              /   * |            \n";
	cout<<"                             /     *             \n";
	cout<<"                             |*   /              \n";
	color(hConsole, 1);
	cout<<"                             | * /|* _________        \n";
	cout<<"                             |__/_|__*_______/      \n";
	cout<<"                             |_/__|____*____/        \n";
	cout<<"                             |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                               *__|______*/          \n";
	cout<<"                                * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	12
color(hConsole, 5);
	cout<<"                                              \n";
	cout<<"                                /|*                  \n";
	cout<<"                               /_|___*                \n";
	cout<<"                              /__|___|             \n";
	cout<<"                                 |___|              \n";
	color(hConsole, 6);
	cout<<"                                /*   |             \n";
	cout<<"                               /   * |            \n";
	cout<<"                              /     *             \n";
	cout<<"                              |*   /              \n";
	color(hConsole, 1);
	cout<<"                              | * /|* _________        \n";
	cout<<"                              |__/_|__*_______/      \n";
	cout<<"                              |_/__|____*____/        \n";
	cout<<"                              |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                *__|______*/          \n";
	cout<<"                                 * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	13
color(hConsole, 5);
	cout<<"                                               \n";
	cout<<"                                 /|*                  \n";
	cout<<"                                /_|___*                \n";
	cout<<"                               /__|___|             \n";
	cout<<"                                  |___|              \n";
	color(hConsole, 6);
	cout<<"                                 /*   |             \n";
	cout<<"                                /   * |            \n";
	cout<<"                               /     *             \n";
	cout<<"                               |*   /              \n";
	color(hConsole, 1);
	cout<<"                               | * /|* _________        \n";
	cout<<"                               |__/_|__*_______/      \n";
	cout<<"                               |_/__|____*____/        \n";
	cout<<"                               |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                 *__|______*/          \n";
	cout<<"                                  * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	14
color(hConsole, 5);
	cout<<"                                                \n";
	cout<<"                                  /|*                  \n";
	cout<<"                                 /_|___*                \n";
	cout<<"                                /__|___|             \n";
	cout<<"                                   |___|              \n";
	color(hConsole, 6);
	cout<<"                                  /*   |             \n";
	cout<<"                                 /   * |            \n";
	cout<<"                                /     *             \n";
	cout<<"                                |*   /              \n";
	color(hConsole, 1);
	cout<<"                                | * /|* _________        \n";
	cout<<"                                |__/_|__*_______/      \n";
	cout<<"                                |_/__|____*____/        \n";
	cout<<"                                |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                  *__|______*/          \n";
	cout<<"                                   * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	15
color(hConsole, 5);
	cout<<"                                                 \n";
	cout<<"                                   /|*                  \n";
	cout<<"                                  /_|___*                \n";
	cout<<"                                 /__|___|             \n";
	cout<<"                                    |___|              \n";
	color(hConsole, 6);
	cout<<"                                   /*   |             \n";
	cout<<"                                  /   * |            \n";
	cout<<"                                 /     *             \n";
	cout<<"                                 |*   /              \n";
	color(hConsole, 1);
	cout<<"                                 | * /|* _________        \n";
	cout<<"                                 |__/_|__*_______/      \n";
	cout<<"                                 |_/__|____*____/        \n";
	cout<<"                                 |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                   *__|______*/          \n";
	cout<<"                                    * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	16
color(hConsole, 5);
	cout<<"                                                  \n";
	cout<<"                                    /|*                  \n";
	cout<<"                                   /_|___*                \n";
	cout<<"                                  /__|___|             \n";
	cout<<"                                     |___|              \n";
	color(hConsole, 6);
	cout<<"                                    /*   |             \n";
	cout<<"                                   /   * |            \n";
	cout<<"                                  /     *             \n";
	cout<<"                                  |*   /              \n";
	color(hConsole, 1);
	cout<<"                                  | * /|* _________        \n";
	cout<<"                                  |__/_|__*_______/      \n";
	cout<<"                                  |_/__|____*____/        \n";
	cout<<"                                  |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                    *__|______*/          \n";
	cout<<"                                     * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	17
color(hConsole, 5);
	cout<<"                                                   \n";
	cout<<"                                     /|*                  \n";
	cout<<"                                    /_|___*                \n";
	cout<<"                                   /__|___|             \n";
	cout<<"                                      |___|              \n";
	color(hConsole, 6);
	cout<<"                                     /*   |             \n";
	cout<<"                                    /   * |            \n";
	cout<<"                                   /     *             \n";
	cout<<"                                   |*   /              \n";
	color(hConsole, 1);
	cout<<"                                   | * /|* _________        \n";
	cout<<"                                   |__/_|__*_______/      \n";
	cout<<"                                   |_/__|____*____/        \n";
	cout<<"                                   |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                     *__|______*/          \n";
	cout<<"                                      * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	18
color(hConsole, 5);
	cout<<"                                                    \n";
	cout<<"                                      /|*                  \n";
	cout<<"                                     /_|___*                \n";
	cout<<"                                    /__|___|             \n";
	cout<<"                                       |___|              \n";
	color(hConsole, 6);
	cout<<"                                      /*   |             \n";
	cout<<"                                     /   * |            \n";
	cout<<"                                    /     *             \n";
	cout<<"                                    |*   /              \n";
	color(hConsole, 1);
	cout<<"                                    | * /|* _________        \n";
	cout<<"                                    |__/_|__*_______/      \n";
	cout<<"                                    |_/__|____*____/        \n";
	cout<<"                                    |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                      *__|______*/          \n";
	cout<<"                                       * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	19
color(hConsole, 5);
	cout<<"                                                     \n";
	cout<<"                                       /|*                  \n";
	cout<<"                                      /_|___*                \n";
	cout<<"                                     /__|___|             \n";
	cout<<"                                        |___|              \n";
	color(hConsole, 6);
	cout<<"                                       /*   |             \n";
	cout<<"                                      /   * |            \n";
	cout<<"                                     /     *             \n";
	cout<<"                                     |*   /              \n";
	color(hConsole, 1);
	cout<<"                                     | * /|* _________        \n";
	cout<<"                                     |__/_|__*_______/      \n";
	cout<<"                                     |_/__|____*____/        \n";
	cout<<"                                     |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                       *__|______*/          \n";
	cout<<"                                        * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	20
color(hConsole, 5);
	cout<<"                                                      \n";
	cout<<"                                        /|*                  \n";
	cout<<"                                       /_|___*                \n";
	cout<<"                                      /__|___|             \n";
	cout<<"                                         |___|              \n";
	color(hConsole, 6);
	cout<<"                                        /*   |             \n";
	cout<<"                                       /   * |            \n";
	cout<<"                                      /     *             \n";
	cout<<"                                      |*   /              \n";
	color(hConsole, 1);
	cout<<"                                      | * /|* _________        \n";
	cout<<"                                      |__/_|__*_______/      \n";
	cout<<"                                      |_/__|____*____/        \n";
	cout<<"                                      |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                        *__|______*/          \n";
	cout<<"                                         * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
//	21
	color(hConsole, 5);
	cout<<"                                                       \n";
	cout<<"                                         /|*                  \n";
	cout<<"                                        /_|___*                \n";
	cout<<"                                       /__|___|             \n";
	cout<<"                                          |___|              \n";
	color(hConsole, 6);
	cout<<"                                         /*   |             \n";
	cout<<"                                        /   * |            \n";
	cout<<"                                       /     *             \n";
	cout<<"                                       |*   /              \n";
	color(hConsole, 1);
	cout<<"                                       | * /|* _________        \n";
	cout<<"                                       |__/_|__*_______/      \n";
	cout<<"                                       |_/__|____*____/        \n";
	cout<<"                                       |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                         *__|______*/          \n";
	cout<<"                                          * |_______*              \n";
	Beep(500,600);
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";	
//	22
	color(hConsole, 5);
	cout<<"                                                        \n";
	cout<<"                                          /|*                  \n";
	cout<<"                                         /_|___*                \n";
	cout<<"                                        /__|___|             \n";
	cout<<"                                           |___|              \n";
	color(hConsole, 6);
	cout<<"                                          /*   |             \n";
	cout<<"                                         /   * |            \n";
	cout<<"                                        /     *             \n";
	cout<<"                                        |*   /              \n";
	color(hConsole, 1);
	cout<<"                                        | * /|* _________        \n";
	cout<<"                                        |__/_|__*_______/      \n";
	cout<<"                                        |_/__|____*____/        \n";
	cout<<"                                        |/___|_____*__/         \n";
	color(hConsole, 2);
	cout<<"                                          *__|______*/          \n";
	cout<<"                                           * |_______*              \n";
	Beep(500,600);
	return 0;
}
